// Auto-generated from main.html.
// DO NOT EDIT.

library main_html;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

import '_footer.html.dart';
import '_footer.html.x_todo_footer.dart';
import '_item.html.dart';
import '_item.html.x_todo_row.dart';
import '_newform.html.dart';
import '_newform.html.x_todo_form.dart';
import '_toggleall.html.dart';
import '_toggleall.html.x_toggle_all.dart';

// Original code

import 'dart:html';
import 'model.dart';
import 'package:web_components/watcher.dart';

main() {
  // listen on changes to #hash in the URL
  // Note: listen on both popState and hashChange, because IE9 doens't support
  // history API, and it doesn't work properly on Opera 12.
  // See http://dartbug.com/5483
  updateFilters(e) {
    viewModel.showIncomplete = window.location.hash != '#/completed';
    viewModel.showDone = window.location.hash != '#/active';
    dispatch();
  }
  window.on.hashChange.add(updateFilters);
  window.on.popState.add(updateFilters);
}

// Additional generated code

var ___e0;

var ___e1;

var ___e4;

// Fields for template list '__e-4'
autogenerated.Element _childTemplate___e4;
autogenerated.WatcherDisposer _stopWatcher___e4;
List<autogenerated.WatcherDisposer> _removeChild___e4;

var ___e5;

// Fields for template conditional '__e-5'
autogenerated.WatcherDisposer _stopWatcher_if___e5;
autogenerated.Element _childTemplate___e5;
autogenerated.Element _parent___e5;
autogenerated.Element _child___e5;
String _childId___e5;

var _footer;

/** Create the views and bind them to models. */
void init_autogenerated() {
  // Create view.
  var _root = new autogenerated.DocumentFragment.html(_INITIAL_PAGE);
  
  // Initialize fields.
  ___e0 = _root.query('#__e-0');
  
  var component___e0 = new FormComponent.forElement(___e0);
  
  component___e0.created_autogenerated();
  
  ___e1 = _root.query('#__e-1');
  
  var component___e1 = new ToggleComponent.forElement(___e1);
  
  component___e1.created_autogenerated();
  
  ___e4 = _root.query('#__e-4');
  
  assert(___e4.elements.length == 1);
  _childTemplate___e4 = ___e4.elements[0];
  _removeChild___e4 = [];
  ___e4.nodes.clear();
  
  ___e5 = _root.query('#__e-5');
  
  assert(___e5.elements.length == 1);
  _childTemplate___e5 = ___e5.elements[0];
  _childId___e5 = _childTemplate___e5.id;
  if (_childId___e5 != null && _childId___e5 != '') {
    _childTemplate___e5.id = '';
  }
  ___e5.style.display = 'none';
  ___e5.nodes.clear();
  
  // Attach model to views.
  ___e0.xtag.inserted_autogenerated();
  
  ___e1.xtag.inserted_autogenerated();
  
  _stopWatcher___e4 = autogenerated.watchAndInvoke(
  () => app.todos, (e) {
    for (var remover in _removeChild___e4) remover();
    _removeChild___e4.clear();
    if (app.todos is Iterable) {
      for (var x in app.todos) {
        var child___e4 = _childTemplate___e4.clone(true);
        
        var ___e3;
        // Fields for template conditional '__e-3'
        autogenerated.WatcherDisposer _stopWatcher_if___e3;
        autogenerated.Element _childTemplate___e3;
        autogenerated.Element _parent___e3;
        autogenerated.Element _child___e3;
        String _childId___e3;
        
        var ___e2;
        
        if (child___e4.id == "__e-3") {
          ___e3 = child___e4;
        } else {
          ___e3 = child___e4.query('#__e-3');
        }
        assert(___e3.elements.length == 1);
        _childTemplate___e3 = ___e3.elements[0];
        _childId___e3 = _childTemplate___e3.id;
        if (_childId___e3 != null && _childId___e3 != '') {
          _childTemplate___e3.id = '';
        }
        ___e3.style.display = 'none';
        ___e3.nodes.clear();
        
        ___e4.parent.nodes.add(child___e4);
        
        // Attach listeners/watchers
        
        _stopWatcher_if___e3 = autogenerated.watchAndInvoke(() => viewModel.isVisible(x), (e) {
          bool showNow = e.newValue;
          if (_child___e3 != null && !showNow) {
            // Remove any listeners/watchers on children
            
            ___e2.xtag.removed_autogenerated();
            
            // Remove the actual child
            _child___e3.remove();
            _child___e3 = null;
          } else if (_child___e3 == null && showNow) {
            _child___e3 = _childTemplate___e3.clone(true);
            if (_childId___e3 != null && _childId___e3 != '') {
              _child___e3.id = _childId___e3;
            }
            // Initialize children
            
            if (_child___e3.id == "__e-2") {
              ___e2 = _child___e3;
            } else {
              ___e2 = _child___e3.query('#__e-2');
            }
            var component___e2 = new TodoItemComponent.forElement(___e2);
            component___e2.todo = x;
            component___e2.created_autogenerated();
            
            ___e3.parent.nodes.add(_child___e3);
            // Attach listeners/watchers
            ___e2.xtag.inserted_autogenerated();
            
          }
        });
        
        // Remember to unregister them
        
        _removeChild___e4.add(() {
          
          child___e4.remove();
          
          _stopWatcher_if___e3();
          if (_child___e3 != null) {
            _child___e3.remove();
            // Remove any listeners/watchers on children
            
            ___e2.xtag.removed_autogenerated();
            
          }
          
        });
      }
    }
  });
  
  _stopWatcher_if___e5 = autogenerated.watchAndInvoke(() => viewModel.hasElements, (e) {
    bool showNow = e.newValue;
    if (_child___e5 != null && !showNow) {
      // Remove any listeners/watchers on children
      
      _footer.xtag.removed_autogenerated();
      
      // Remove the actual child
      _child___e5.remove();
      _child___e5 = null;
    } else if (_child___e5 == null && showNow) {
      _child___e5 = _childTemplate___e5.clone(true);
      if (_childId___e5 != null && _childId___e5 != '') {
        _child___e5.id = _childId___e5;
      }
      // Initialize children
      
      if (_child___e5.id == "footer") {
        _footer = _child___e5;
      } else {
        _footer = _child___e5.query('#footer');
      }
      var component_footer = new FooterComponent.forElement(_footer);
      component_footer.created_autogenerated();
      
      ___e5.parent.nodes.add(_child___e5);
      
      // Attach listeners/watchers
      
      _footer.xtag.inserted_autogenerated();
      
    }
  });
  
  // Attach view to the document.
  autogenerated.document.body.nodes.add(_root);
}

final String _INITIAL_PAGE = r'''
<section id="todoapp">
<header id="header">
<h1 class="title">todos</h1>
<x-todo-form id="__e-0"></x-todo-form>
</header>
<section id="main">
<x-toggle-all id="__e-1"></x-toggle-all>
<ul id="todo-list">
<template iterate="x in app.todos" id="__e-4">
<template instantiate="if viewModel.isVisible(x)" id="__e-3">
<x-todo-row data-value="todo:x" id="__e-2"></x-todo-row>
</template>
</template>
</ul>
</section>
<template instantiate="if viewModel.hasElements" id="__e-5">
<x-todo-footer id="footer"></x-todo-footer>
</template>
</section>
<footer id="info">
<p>Double-click to edit a todo.</p>
<p>Credits: the <a href="http://www.dartlang.org">Dart</a> team.</p>
<p>
Learn more about
<a href="https://www.dartlang.org/articles/dart-web-components/">Dart + Web Components</a>
or
<a href="https://github.com/dart-lang/dart-web-components/tree/master/example/todomvc">view the source</a>.
</p>
<p>Part of <a href="http://todomvc.com">TodoMVC</a>.</p>
</footer>
''';

