// Auto-generated from toggleall.html.
// DO NOT EDIT.

library x_toggle_all;

import 'dart:html' as autogenerated;
import 'package:web_components/watcher.dart' as autogenerated;

import 'model.dart';
import 'package:web_components/web_component.dart';

class ToggleComponent extends WebComponent {
  
  /** Autogenerated from the template. */
  
  /**
  * Shadow root for this component. We use 'var' to allow simulating shadow DOM
  * on browsers that don't support this feature.
  */
  var _root;
  var _toggleAll;
  
  autogenerated.EventListener _listener_click_1;
  
  autogenerated.WatcherDisposer _stopWatcher_toggleAll_2;
  
  ToggleComponent.forElement(e) : super.forElement(e) {
    _root = createShadowRoot();
  }
  
  void created_autogenerated() {
    if (_root is autogenerated.ShadowRoot) _root.applyAuthorStyles = true;
    
    _root.innerHTML = r'''
    <input id="toggle-all" type="checkbox" checked="{{allChecked}}" data-action="click:markAll">
    <label for="x-toggle-all"></label>
    ''';
    
    _toggleAll = _root.query('#toggle-all');
    
    // Call user-defined created();
    created();
  }
  
  void inserted_autogenerated() {
    _listener_click_1 = (e) {
      markAll(e);
      autogenerated.dispatch();
    };
    _toggleAll.on.click.add(_listener_click_1);
    
    _stopWatcher_toggleAll_2 = autogenerated.watchAndInvoke(() => allChecked, (e) {
      _toggleAll.checked = e.newValue;
    });
    
    // Call user-defined inserted();
    inserted();
  }
  
  void removed_autogenerated() {
    // Call user-defined removed();
    removed();
    
    _toggleAll.on.click.remove(_listener_click_1);
    _listener_click_1 = null;
    
    _stopWatcher_toggleAll_2();
    
  }
  
  /** Original code from the component. */
  
  bool get allChecked => app.todos.length > 0 &&
  app.todos.every((t) => t.done);
  
  void markAll(e) => app.todos.forEach((t) { t.done = _toggleAll.checked; });
}

