// Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/**
 * **Deprecated**: import 'web_ui/templating.dart' instead.
 * Common utility functions used by code generated by the dwc compiler.
 */
@deprecated library templating;

import 'package:meta/meta.dart';
export 'package:web_ui/templating.dart';
