// Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

#library('codegen');

String header(String filename, String libraryName) => """
// Generated Dart class from HTML template $filename.
// DO NOT EDIT.

#library('${libraryName}');

#import('dart:html');
""";

String get commonIncludes => """
#import('package:web_components/lib/js_polyfill/component.dart');
#import('package:web_components/watcher.dart');
#import('package:web_components/lib/js_polyfill/web_components.dart');
#import('package:web_components/tools/lib/data_template.dart');
""";

String componentCode(
    String filename,
    String libraryName,
    String extraImports,
    String className,
    String webComponentName,
    String userCode,
    String generatedCode) => """
${header(filename, libraryName)}
$commonIncludes
$extraImports

class $className extends Component {
  /** User written code associated with '$filename'. */
$userCode
  /** Autogenerated from the template. */
$generatedCode
}
""";
