// Generated Dart class from HTML template toggleall.html.
// DO NOT EDIT.

#library('toggleall_html');

#import('dart:html');
#import('../../../component.dart');
#import('../../../watcher.dart');

/** Below import from script tag in HTML file. */
#import('model.dart');

class ToggleComponent extends Component {
  /** User written code associated with this component 'toggleall.html'. */
  bool get allChecked () => app.todos.length > 0 &&
      app.todos.every((t) => t.done);

  void markAll() => app.todos.forEach((t) { t.done = _toggleAll.checked; });

  /** Autogenerated from the template. */
  ToggleComponent() : super('toggleall');

  InputElement _toggleAll; // Name generated from the id from the element.
  WatcherDisposer _stopWatcher1;
  EventListener _listener1;

  void created(ShadowRoot shadowRoot)  {
    root = shadowRoot;
    _toggleAll = root.query("#toggle-all");
  }

  void inserted() {
    _listener1 = (_) {
      markAll();
      _toggleAll.checked = allChecked;
      dispatch();
    };
    _toggleAll.on.click.add(_listener1);
    _stopWatcher1 = bind(() => allChecked, (e) {
      _toggleAll.checked = e.newValue;
    });
  }

  void removed() {
    _toggleAll.on.click.remove(_listener1);
    _stopWatcher1();
  }
}
