// Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

library compile;

import 'dart:coreimpl';
import 'package:html5lib/dom.dart';
import 'package:html5lib/html5parser.dart';
import 'package:html5lib/tokenizer.dart';

import 'analyzer.dart';
import 'code_printer.dart';
import 'emitters.dart';
import 'file_system.dart';
import 'info.dart';
import 'source_file.dart';
import 'utils.dart';
import 'world.dart';

// TODO(jmesserly): move these things into html5lib's public api
// This is for voidElements:
import 'package:html5lib/src/constants.dart' as html5_constants;
// This is for htmlEscapeMinimal:
import 'package:html5lib/src/utils.dart' as html5_utils;


Document parseHtml(String template, String sourcePath) {
  var parser = new HTMLParser();
  var document = parser.parse(new HTMLTokenizer(template));

  // Note: errors aren't fatal in HTML (unless strict mode is on).
  // So just print them as warnings.
  for (var e in parser.errors) {
    world.warning('$sourcePath line ${e.line}:${e.column}: ${e.message}');
  }
  return document;
}

/**
 * Walk the tree produced by the parser looking for templates, expressions, etc.
 * as a prelude to emitting the code for the template.
 */
class Compile {
  final FileSystem filesystem;
  final List<SourceFile> files;

  /** Information about source [files] given their href. */
  final Map<String, FileInfo> info;

  /** Used by template tool to open a file. */
  Compile(this.filesystem)
      : files = <SourceFile>[],
        info = new SplayTreeMap<String, FileInfo>();

  /** Compile the application starting from the given [mainFile]. */
  void run(String mainFile, [String baseDir = ""]) {
    _parseAndDiscover(mainFile, baseDir);
    _analyze();
    _emit();
  }

  /**
   * Parse [mainFile] and recursively discover web components to load and
   * parse.
   */
  void _parseAndDiscover(String mainFile, String baseDir) {
    var pending = new Queue<String>(); // files to process
    pending.addLast(mainFile);
    while (!pending.isEmpty()) {
      var filename = pending.removeFirst();

      // Parse the file.
      if (info.containsKey(filename)) continue;
      var file = _parseFile(filename, baseDir, filename == mainFile);
      files.add(file);

      // Find additional components being loaded.
      var fileInfo = time('Analyzed definitions ${file.filename}',
          () => analyzeDefinitions(file));
      info[file.filename] = fileInfo;
      for (var href in fileInfo.componentLinks) {
        pending.addLast(href);
      }
    }
  }

  /** Parse [filename] and treat it as a component if [isComponent] is true. */
  SourceFile _parseFile(String filename, String baseDir, bool mainDocument) {
    var file = new SourceFile(filename, mainDocument);
    var source = filesystem.readAll("$baseDir/$filename");
    file.document = time("Parsed $filename", () => parseHtml(source, filename));
    if (options.dumpTree) {
      print("\n\n Dump Tree $filename:\n\n");
      print(file.document.outerHTML);
      print("\n=========== End of AST ===========\n\n");
    }
    return file;
  }

  /** Run the analyzer on every input html file. */
  void _analyze() {
    for (var file in files) {
      time('Analyzed contents ${file.filename}', () => analyzeFile(file, info));
    }
  }

  /** Emit the generated code corresponding to each input file. */
  void _emit() {
    for (var file in files) {
      var fileInfo = info[file.filename];
      time('Codegen ${file.filename}', () {
        _removeScriptTags(file.document);
        if (file.mainDocument) {
          fileInfo.generatedCode =
              new MainPageEmitter(fileInfo).run(file.document);
          fileInfo.generatedHtml = _emitMainHtml(file);
        } else {
          fileInfo.generatedCode = emitComponents(fileInfo);
          fileInfo.generatedHtml = _emitComponentHtml(file);
        }
      });
    }
  }


  /** Generate an html file declaring a web component. */
  String _emitComponentHtml(SourceFile file) {
    _addAutoGeneratedComment(file);
    return file.document.outerHTML;
  }

  static const String DARTJS_LOADER =
    "http://dart.googlecode.com/svn/branches/bleeding_edge/dart/client/dart.js";

  /** Generate an html file with the (trimmed down) main html page. */
  String _emitMainHtml(SourceFile file) {
    var dartFilename = info[file.filename].dartFilename;

    // Clear the body, we moved all of it
    var document = file.document;
    document.body.nodes.clear();
    document.body.nodes.add(parseFragment(
      '<script type="text/javascript" src="$DARTJS_LOADER"></script>'
      '<script type="application/dart" src="$dartFilename"></script>'
    ));

    for (var link in document.head.queryAll('link')) {
      if (link.attributes["rel"] == "components") {
        link.remove();
      }
    }

    _addAutoGeneratedComment(file);
    return document.outerHTML;
  }

  void _removeScriptTags(Document doc) {
    for (var tag in doc.queryAll('script')) {
      if (tag.attributes['type'] == 'application/dart') {
        tag.remove();
      }
    }
  }
}

void _addAutoGeneratedComment(SourceFile file) {
  var document = file.document;

  // Insert the "auto-generated" comment after the doctype, otherwise IE will go
  // into quirks mode.
  int commentIndex = 0;
  DocumentType doctype = find(document.nodes, (n) => n is DocumentType);
  if (doctype != null) {
    commentIndex = document.nodes.indexOf(doctype) + 1;
    // TODO(jmesserly): the html5lib parser emits a warning for missing doctype,
    // but it allows you to put it after comments. Presumably they do this
    // because some comments won't force IE into quirks mode (sigh). See this
    // link for more info:
    //     http://bugzilla.validator.nu/show_bug.cgi?id=836
    // For simplicity we're emitting the warning always, like validator.nu does.
    if (doctype.tagName != 'html' || commentIndex != 1) {
      world.warning('${file.filename}: file should start with <!DOCTYPE html> '
          'to avoid the possibility of it being parsed in quirks mode in IE. '
          'See http://www.w3.org/TR/html5-diff/#doctype');
    }
  }
  document.nodes.insertAt(commentIndex, parseFragment(
      '\n<!-- This file was auto-generated from template '
              '${file.filename}. -->\n'));
}
