// Copyright (c) 2012, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

library source_file;

import 'package:html5lib/dom.dart';
import 'info.dart';

/** An input file to process by the template compiler. */
class SourceFile {
  final String filename;

  final bool isDart;
  final bool isMainHtml;
  Document document;
  String code;

  SourceFile(this.filename, {this.isDart: false, this.isMainHtml: true});

  String toString() => "<#SourceFile $filename>";
}

/** An output file to generated by the template compiler. */
class OutputFile {
  final String filename;
  final String contents;

  OutputFile(this.filename, this.contents);
}
